# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f3edf837dae730ac8f88eab6035d0d9c09ebb00e23779dfd44fa6d0023b48268e00e7067ba438d91d58986854504f73aaaa40951760196a4c79cf13da51bc6e

test:
  secret_key_base: 8f3d6f67a21674b13c385568ee183e262c5009ca281f64fe415f265ccf20e3f42e1e33adf4fdb1a361b7ccc60e1a8da24c74f66e07ac5b40e32c423119cb56fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
